Teshca.DotNet.AspNetCore.Mvc/Models/ErrorViewModel.cs
using System;

namespace Teshca.DotNet.AspNetCore.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teshca.DotNet.AspNetCore.Mvc/ViewModels/LocalizationViewModel.cs
using System;
namespace Teshca.DotNet.AspNetCore.Mvc.ViewModels
{
    public class LocalizationViewModel
    {
        public LocalizationViewModel()
        {
        }

        public string MyHelloWorld { get; set; }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Areas/Identity/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace Teshca.DotNet.AspNetCore.Mvc.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;

        public RegisterModel(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { area = "Identity", userId = user.Id, code = code, returnUrl = returnUrl },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", new { email = Input.Email, returnUrl = returnUrl });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Teshca.DotNet.AspNetCore.Mvc.Models;

namespace Teshca.DotNet.AspNetCore.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cookies()
        {
            ViewBag.Cookies = Request.Cookies;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult MyAction(int id)
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Controllers/IdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Teshca.DotNet.AspNetCore.Mvc.Controllers
{
    public class IdentityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Controllers/LocalizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Teshca.DotNet.AspNetCore.Mvc.ViewModels;

namespace Teshca.DotNet.AspNetCore.Mvc.Controllers
{
    public class LocalizationController : Controller
    {
        private IStringLocalizer<LocalizationController> _stringLocalizer;

        public LocalizationController(IStringLocalizer<LocalizationController> stringLocalizer)
        {
            _stringLocalizer = stringLocalizer;
        }

        public IActionResult Index()
        {
            LocalizationViewModel vm = new LocalizationViewModel();
            vm.MyHelloWorld = _stringLocalizer.GetString("MyHelloWorld");
            return View(vm);
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Controllers/ScaffoldingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Teshca.DotNet.AspNetCore.Mvc.Controllers
{
    public class ScaffoldingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Controllers/TagHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Teshca.DotNet.AspNetCore.Mvc.Controllers
{
    public class TagHelpersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Teshca.DotNet.AspNetCore.Mvc/Views/Home/Cookies.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Cookies</h1>

    <dl>
        @foreach (var cookie in ViewBag.Cookies)
        {
            <dt>@cookie.Key</dt>
            <dd>@cookie.Value</dd>
        }
    </dl>
    
</div>

Teshca.DotNet.AspNetCore.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <environment names="Development">
        Application is running in Development environment.
        Change launchSettings.json file to change environment in Visual Studio.
    </environment>

    <environment names="Production">
        Application is running in Production environment.
        Change launchSettings.json file to change environment in Visual Studio.
    </environment>

    <a asp-action="Cookies">Cookies</a>

</div>

Teshca.DotNet.AspNetCore.Mvc/Views/Home/MyAction.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@Context.Request.Query["id"]

Teshca.DotNet.AspNetCore.Mvc/Views/Localization/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@model Teshca.DotNet.AspNetCore.Mvc.ViewModels.LocalizationViewModel
@inject IViewLocalizer Localizer

<h3>Localization</h3>

<h4>Basic steps performed to configure localization for controllers:</h4>

<ul>
    <li>Add NuGet package of Microsoft.Extensions.Localization</li>
    <li>
        Register Services:
        <pre><code data-language="csharp">services.AddLocalization(options => options.ResourcesPath = "Resources");</code></pre>
    </li>
    <li>
        Setup Middleware:
        <pre><code data-language="csharp">app.UseRequestLocalization();</code></pre>
    </li>
    <li>
        Add Resources/Controllers/LocalizationController.resx file with following key:
        <pre><code data-language="html"><data name="MyHelloWorld" xml:space="preserve">
        <value>Hello World in English</value>
	</data></code></pre>
    </li>
    <li>
        Read localized string in LocalizationController:
        <pre><code data-language="csharp">private IStringLocalizer&lt;LocalizationController> _stringLocalizer;
            ...
            _stringLocalizer.GetString("MyHelloWorld");</code></pre>
    </li>
    <li>
        Read in View:
        <pre><code data-language="csharp">@@Model.MyHelloWorld</code></pre>
    </li>
    <li>
        Output in View:
        <samp>@Model.MyHelloWorld</samp>
    </li>
</ul>

<h4>Steps performed differently to configure localization for views:</h4>

<ul>
    <li>
        Register Services:
        <pre><code data-language="csharp">services.AddControllersWithViews()
                .AddViewLocalization(options => options.ResourcesPath = "Resources");</code></pre>
    </li>
    <li>
        Add Resources/Views/Localization/Index.resx file with following key:
        <pre><code data-language="html"><data name="MyViewHelloWorld" xml:space="preserve">
		<value>Hello World in English for view</value>
	</data></code></pre>
    </li>
    <li>
        Read in View:
        <pre><code data-language="csharp">@@inject IViewLocalizer Localizer
            @@Localizer["MyViewHelloWorld"]</code></pre>
    </li>
    <li>
        Output in View:
        <samp>@Localizer["MyViewHelloWorld"]</samp>
    </li>
</ul>




Teshca.DotNet.AspNetCore.Mvc/Views/Scaffolding/Index.cshtml
<h3>Scaffolding (aspnet-codegenerator)</h3>

<h5>Following gives error when path has space in it:</h5>
dotnet tool install -g dotnet-aspnet-codegenerator

<h5>Add Microsoft.VisualStudio.Web.CodeGeneration.Design NuGet package reference</h5>
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

<h5>Generate Controller Code:</h5>
dotnet aspnet-codegenerator controller -name ScaffoldingController -outDir Controllers

<h5>Generate View Code:</h5>
dotnet aspnet-codegenerator view Index Empty  -outDir Views/Scaffolding

<h5>Add Asp.Net Core Identity Authentication in MVC Project:</h5>
<pre>
    dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore
    dotnet add package Microsoft.AspNetCore.Identity.UI
    dotnet add package Microsoft.EntityFrameworkCore.Sqlite
    dotnet add package Microsoft.EntityFrameworkCore.Tools
    dotnet aspnet-codegenerator identity --useDefaultUI
</pre>
<li>Views/Shared/_LoginPartial.cshtml</li>
<li>
    appSettings.json
    "ConnectionStrings": {
    "IdentityDataContextConnection": "Data Source=Teshca.DotNet.AspNetCore.Mvc.db"
    }
</li>
<pre>
    Areas/Identity/IdentityHostingStartup.cs
    Areas/Identity/Data/IdentityDataContext.cs
    Areas/Identity/Pages/_ValidationScriptsPartial.cshtml
    Areas/Identity/Pages/_ViewStart.cshtml
</pre>
<pre>
dotnet ef migrations add CreateIdentitySchema
dotnet ef database update
</pre>

Teshca.DotNet.AspNetCore.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teshca.DotNet.AspNetCore.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/github.css" rel="stylesheet" type="text/css" />
    @RenderSection("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teshca.DotNet.AspNetCore.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TagHelpers" asp-action="Index">TagHelpers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Localization" asp-action="Index">Localization</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scaffolding" asp-action="Index">Scaffoliding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Index">Identity</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Teshca.DotNet.AspNetCore.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="js/rainbow-custom.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Teshca.DotNet.AspNetCore.Mvc/Views/TagHelpers/Index.cshtml
@using System.Web;
@addTagHelper Teshca.DotNet.AspNetCore.Mvc.CustomTagHelpers.*, Teshca.DotNet.AspNetCore.Mvc

@section Head {
    <link href="~/css/github.css" rel="stylesheet" type="text/css" />
}

<h3>Anchor Tag Helper</h3>

<pre><code data-language="html">&lt;a asp-controller="Home" asp-action="MyAction" asp-route-id="1">Home My Action With Id 1&lt;/a></code></pre>
<pre><code data-language="html"><a asp-controller="Home" asp-action="MyAction" asp-route-id="1">Home My Action With Id 1</a></code></pre>
<samp><a asp-controller="Home" asp-action="MyAction" asp-route-id="1">Home My Action With Id 1</a></samp>

<h3>Custom Tag Helper</h3>

<pre><code data-language="html">&lt;my-tag asp-my-attribute="attribute value">&lt;/my-tag></code></pre>
<pre><code data-language="html"><my-tag asp-my-attribute="attribute value"></my-tag></code></pre>
<samp><my-tag asp-my-attribute="attribute value"></my-tag></samp>


@section Scripts {
    
}